---
abstract: 'Number::Format::SouthAsian provides methods to format numbers in the South Asian style.'
author:
  - 'Alex Balhatchet (alex@lokku.com)'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102340, CPAN::Meta::Converter version 2.102160'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Number-Format-SouthAsian
version: 0.01
